const keyboardKeys = [

    { id: "Backquote", en: { text: "`", textShift: "~"}, ru: { text: "ё", textShift: "Ё"} },
    { id: "Digit1", en: { text: "1", textShift: "!"}, ru: { text: "1", textShift: "!"} },
    { id: "Digit2", en: { text: "2", textShift: "@"}, ru: { text: "2", textShift: '"'} },
    { id: "Digit3", en: { text: "3", textShift: "#"}, ru: { text: "3", textShift: "№"} },
    { id: "Digit4", en: { text: "4", textShift: "$"}, ru: { text: "4", textShift: ";"} },
    { id: "Digit5", en: { text: "5", textShift: "%"}, ru: { text: "5", textShift: "%"} },
    { id: "Digit6", en: { text: "6", textShift: "^"}, ru: { text: "6", textShift: ":"} },
    { id: "Digit7", en: { text: "7", textShift: "&"}, ru: { text: "7", textShift: "?"} },
    { id: "Digit8", en: { text: "8", textShift: "*"}, ru: { text: "8", textShift: "*"} },
    { id: "Digit9", en: { text: "9", textShift: "("}, ru: { text: "9", textShift: "("} },
    { id: "Digit0", en: { text: "0", textShift: ")"}, ru: { text: "0", textShift: ")"} },
    { id: "Minus", en: { text: "-", textShift: "_"}, ru: { text: "-", textShift: "_"} },
    { id: "Equal", en: { text: "=", textShift: "+"}, ru: { text: "=", textShift: "+"} },
    { id: "Backspace", en: { text: "Backspace", textShift: "Backspace"}, ru: { text: "Backspace", textShift: "Backspace"} },

    { id: "Tab", en: { text: "Tab", textShift: "Tab"}, ru: { text: "Tab", textShift: "Tab"} },
    { id: "KeyQ", en: { text: "q", textShift: "Q"}, ru: { text: "й", textShift: "Й"} },
    { id: "KeyW", en: { text: "w", textShift: "W"}, ru: { text: "ц", textShift: "Ц"} },
    { id: "KeyE", en: { text: "e", textShift: "E"}, ru: { text: "у", textShift: "У"} },
    { id: "KeyR", en: { text: "r", textShift: "R"}, ru: { text: "к", textShift: "К"} },
    { id: "KeyT", en: { text: "t", textShift: "T"}, ru: { text: "е", textShift: "Е"} },
    { id: "KeyY", en: { text: "y", textShift: "Y"}, ru: { text: "н", textShift: "Н"} },
    { id: "KeyU", en: { text: "u", textShift: "U"}, ru: { text: "г", textShift: "Г"} },
    { id: "KeyI", en: { text: "i", textShift: "I"}, ru: { text: "ш", textShift: "Ш"} },
    { id: "KeyO", en: { text: "o", textShift: "O"}, ru: { text: "щ", textShift: "Щ"} },
    { id: "KeyP", en: { text: "p", textShift: "P"}, ru: { text: "з", textShift: "З" } },
    { id: "BracketLeft", en: { text: "[", textShift: "{"}, ru: { text: "х", textShift: "Х"} },
    { id: "BracketRight", en: { text: "]", textShift: "}"}, ru: { text: "ъ", textShift: "Ъ" } },
    { id: "Backslash", en: { text: "\\", textShift: "|"}, ru: { text: "\\", textShift: "/"} },
    { id: "Delete", en: { text: "Del", textShift: "Del"}, ru: { text: "Del", textShift: "Del"} },

    { id: "CapsLock", en: { text: "CapsLock", textShift: "CapsLock"}, ru: { text: "CapsLock", textShift: "CapsLock"} },
    { id: "KeyA", en: { text: "a", textShift: "A"}, ru: { text: "ф", textShift: "Ф"} },
    { id: "KeyS", en: { text: "s", textShift: "S"}, ru: { text: "ы", textShift: "Ы"} },
    { id: "KeyD", en: { text: "d", textShift: "D"}, ru: { text: "в", textShift: "В"} },
    { id: "KeyF", en: { text: "f", textShift: "F"}, ru: { text: "а", textShift: "А" } },
    { id: "KeyG", en: { text: "g", textShift: "G"}, ru: { text: "п", textShift: "П"} },
    { id: "KeyH", en: { text: "h", textShift: "H"}, ru: { text: "р", textShift: "Р"} },
    { id: "KeyJ", en: { text: "j", textShift: "J"}, ru: { text: "о", textShift: "О"} },
    { id: "KeyK", en: { text: "k", textShift: "K"}, ru: { text: "л", textShift: "Л"} },
    { id: "KeyL", en: { text: "l", textShift: "L"}, ru: { text: "д", textShift: "Д"} },
    { id: "Semicolon", en: { text: ";", textShift: ":"}, ru: { text: "ж", textShift: "Ж"} },
    { id: "Quote", en: { text: "'", textShift: '"'}, ru: { text: "э", textShift: "Э",} },
    { id: "Enter", en: { text: "Enter", textShift: "Enter"}, ru: { text: "Enter", textShift: "Enter"} },

    { id: "ShiftLeft", en: { text: "Shift", textShift: "Shift"}, ru: { text: "Shift", textShift: "Shift"} },
    { id: "KeyZ", en: { text: "z", textShift: "Z"}, ru: { text: "я", textShift: "Я"} },
    { id: "KeyX", en: { text: "x", textShift: "X"}, ru: { text: "ч", textShift: "Ч"} },
    { id: "KeyC", en: { text: "c", textShift: "C"}, ru: { text: "с", textShift: "С"} },
    { id: "KeyV", en: { text: "v", textShift: "V"}, ru: { text: "м", textShift: "М"} },
    { id: "KeyB", en: { text: "b", textShift: "B"}, ru: { text: "и", textShift: "И"} },
    { id: "KeyN", en: { text: "n", textShift: "N"}, ru: { text: "т", textShift: "Т"} },
    { id: "KeyM", en: { text: "m", textShift: "M"}, ru: { text: "ь", textShift: "Ь"} },
    { id: "Comma", en: { text: ",", textShift: ","}, ru: { text: "б", textShift: "Б"} },
    { id: "Period", en: { text: ".", textShift: "."}, ru: { text: "ю", textShift: "Ю"} },
    { id: "Slash", en: { text: "/", textShift: "?"}, ru: { text: ".", textShift: ","} },
    { id: "ShiftRight", en: { text: "Shift", textShift: "Shift"}, ru: { text: "Shift", textShift: "Shift"} },

    { id: "ControlLeft", en: { text: "Ctrl", textShift: "Ctrl"}, ru: { text: "Ctrl", textShift: "Ctrl"} },
    { id: "MetaLeft", en: { text: "Win", textShift: "Win"}, ru: { text: "Win", textShift: "Win"} },
    { id: "AltLeft", en: { text: "Alt", textShift: "Alt"}, ru: { text: "Alt", textShift: "Alt"} },
    { id: "Space", en: { text: "Space", textShift: "Space"}, ru: { text: "Space", textShift: "Space"} },
    { id: "AltRight", en: { text: "Alt", textShift: "Alt"}, ru: { text: "Alt", textShift: "Alt"} },
    { id: "ArrowLeft", en: { text: "◀", textShift: "◀"}, ru: { text: "◀", textShift: "◀"} },
    { id: "ArrowUp", en: { text: "▲", textShift: "▲"}, ru: { text: "▲", textShift: "▲"} },
    { id: "ArrowDown", en: { text: "▼", textShift: "▼"}, ru: { text: "▼", textShift: "▼"} },
    { id: "ArrowRight", en: { text: "▶", textShift: "▶"}, ru: { text: "▶", textShift: "▶"} },
    { id: "ControlRight", en: { text: "Ctrl", textShift: "Ctrl"}, ru: { text: "Ctrl", textShift: "Ctrl"} }
]

export default keyboardKeys
